spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking?createDatabaseIfNotExist=true
    username: spring
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 7000
my:
  secret.string: something

fileStorage : D:\\springbootproject\\files
